# docker-compose.yml
version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: gunicorn web_analytics_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - DB_NAME=analytics
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./web_analytics_frontend
    volumes:
      - ./web_analytics_frontend:/app
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:8000/api
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: npm start

volumes:
  postgres_data:
